"""empty message

Revision ID: 2a06268f017c
Revises: 327e186d0426
Create Date: 2017-08-23 21:20:47.579606

"""

# revision identifiers, used by Alembic.
revision = '2a06268f017c'
down_revision = '327e186d0426'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposition_name', table_name='proposition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_proposition_name', 'proposition', ['name'], unique=False)
    # ### end Alembic commands ###
