"""empty message

Revision ID: 500e950adcc7
Revises: 2a06268f017c
Create Date: 2017-08-25 17:51:11.463913

"""

# revision identifiers, used by Alembic.
revision = '500e950adcc7'
down_revision = '2a06268f017c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposition_link', table_name='proposition')
    op.drop_constraint('senator_facebook_key', 'senator', type_='unique')
    op.drop_constraint('senator_instagram_key', 'senator', type_='unique')
    op.drop_constraint('senator_twitter_key', 'senator', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('senator_twitter_key', 'senator', ['twitter'])
    op.create_unique_constraint('senator_instagram_key', 'senator', ['instagram'])
    op.create_unique_constraint('senator_facebook_key', 'senator', ['facebook'])
    op.create_index('ix_proposition_link', 'proposition', ['link'], unique=False)
    # ### end Alembic commands ###
